include:
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: "split-peripheral input-trackpad-mini input-split"
    artifact-name: torabo_tsuki_lp_nondongle_ball_right_left_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: "nondongle-central split-central input-trackball input-listener input-split-listener"
    artifact-name: torabo_tsuki_lp_nondongle_ball_right_right_central
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: "split-peripheral input-trackpad-mini input-split-secondary-throttled"
    artifact-name: torabo_tsuki_lp_dongle_ball_right_left_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: "split-peripheral input-trackball input-split-throttled"
    artifact-name: torabo_tsuki_lp_dongle_ball_right_right_peripheral
  - board: seeeduino_xiao_ble
    shield: torabo_tsuki_lp_dongle rgbled_adapter
    snippet: "split-central"
    artifact-name: torabo_tsuki_lp_dongle_ball_right_dongle_central
  - board: bmp_boost
    shield: settings_reset
    artifact-name: settings_reset_bmp_boost
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset_xiao_ble
