CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_STATUS_LED=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=9000000
CONFIG_ZMK_NON_LIPO_BATTERY_MANAGEMENT=y
CONFIG_ZMK_NON_LIPO_MIN_MV=1000
CONFIG_ZMK_NON_LIPO_MAX_MV=1350
CONFIG_ZMK_NON_LIPO_LOW_MV=950
CONFIG_ZMK_NON_LIPO_ADV_SLEEP_TIMEOUT=60000

CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
